-- ============================================================================
--  DefectFlow — regional trade presets + region-aware create_organization
--  A "Region" picked at signup seeds the right starter trade list. Cost-centre
--  codes are AU-specific (optional everywhere else). The defect->trade link is
--  the universal spine.
-- ============================================================================

create table if not exists public.trade_presets (
  region text not null,
  sort   int  not null,
  code   text,
  name   text not null,
  primary key (region, sort)
);

-- ── AU (Australia) — the canonical Creation Homes 105, with cost centres ─────
delete from public.trade_presets where region = 'AU';
insert into public.trade_presets (region, sort, code, name) values
('AU',1,'060','Site Security & Waste Management'),
('AU',2,'070','Site Cut & Fill'),
('AU',3,'072','Retaining Walls - Site Prep'),
('AU',4,'080','Site Facilities - Hire Equipment'),
('AU',5,'090','Silt Fence & Temporary Driveway'),
('AU',6,'100','Set Out'),
('AU',7,'110','Electrical Mains'),
('AU',8,'119','Sewer & Water Supply Costs'),
('AU',9,'120','Sewerage & Stormwater Drains'),
('AU',10,'121','Spoil Removal - Drains'),
('AU',11,'130','Rock Breakout and Removal'),
('AU',12,'144','Screw Pile Set Out'),
('AU',13,'145','Piers & Screw Piles - Labour & Materials'),
('AU',14,'150','Concrete Slabs & Footings'),
('AU',15,'160','Termite Proofing - Slab Penetrations'),
('AU',16,'170','Concrete Pump'),
('AU',17,'180','Concrete Cure'),
('AU',18,'190','Site Grade Back - Post Slab'),
('AU',19,'200','Pre-Fab Wall Frames & Roof Truss'),
('AU',20,'204','2-Plank Walkway'),
('AU',21,'205','Perimeter Guardrail'),
('AU',22,'210','Windows & Entry Frames'),
('AU',23,'215','Structural Steel'),
('AU',24,'218','Framing Materials and Hardware'),
('AU',25,'220','Carpenter - Wall Frame & Roof Trusses'),
('AU',26,'222','Crane Hire'),
('AU',27,'224','Void Protection'),
('AU',28,'225','Party & Boundary Wall Systems'),
('AU',29,'226','Party Walls - Labour'),
('AU',30,'230','Metal Fascia & Gutters - Lab & Materials'),
('AU',31,'240','Site Cleaner - OH&S Clean'),
('AU',32,'248','Skylights'),
('AU',33,'250','Roof Tiles (Material & Labour)'),
('AU',34,'255','Sheet Roofing (Material & Labour)'),
('AU',35,'260','Foilwrap to External Walls'),
('AU',36,'265','Scaffolding'),
('AU',37,'270','Plumber (Material & Labour)'),
('AU',38,'280','Brick Sand'),
('AU',39,'290','Bricks'),
('AU',40,'300','Brick Hardware'),
('AU',41,'310','Bricklayer Labour'),
('AU',42,'320','Brick Lintels'),
('AU',43,'330','Box Gutter, Cappings, Flashings'),
('AU',44,'340','Physical Perimeter Termite Barrier'),
('AU',45,'350','Electrical (Material & Labour)'),
('AU',46,'370','Security & Data Systems'),
('AU',47,'390','Internal Lockup Materials'),
('AU',48,'400','Lock Up Hardware'),
('AU',49,'420','Carpenter - Internal Lock-Up'),
('AU',50,'425','External Wall Cladding Materials'),
('AU',51,'426','External Wall Cladding Labour'),
('AU',52,'430','Insulation Batts to Walls'),
('AU',53,'440','Plaster Linings (Materials & Labour)'),
('AU',54,'450','Brick Cleaner'),
('AU',55,'460','Renderer & External Mouldings'),
('AU',56,'470','Staircase'),
('AU',57,'480','Feature Stone Cladding'),
('AU',58,'490','External Lock-Up & Eaves Materials'),
('AU',59,'495','Carpenter - External Lock-Up & Eaves'),
('AU',60,'500','Internal Doors & 2nd Fix Mouldings'),
('AU',61,'510','Fix Hardware'),
('AU',62,'523','Balcony Materials'),
('AU',63,'524','Balcony Labour'),
('AU',64,'525','Balustrades'),
('AU',65,'530','Carpenter - Fix Out'),
('AU',66,'540','Site Cleaner - 1st'),
('AU',67,'550','Waterproofing'),
('AU',68,'560','Cabinets'),
('AU',69,'570','Painter - Labour and Materials'),
('AU',70,'590','Painter - Quality Assurance Retention'),
('AU',71,'600','Ceramic Tiles - Supply'),
('AU',72,'610','Wall & Floor Tiles Labour'),
('AU',73,'620','Kitchen Sinks'),
('AU',74,'630','Robes, Shower Screens, Mirrors, Splashbacks'),
('AU',75,'640','Fit-Off Hardware & Door Furniture'),
('AU',76,'650','Carpenter - Fit-Off'),
('AU',77,'660','Garage Doors'),
('AU',78,'670','Gas Heating Systems'),
('AU',79,'680','Cooling Systems'),
('AU',80,'690','Toilet Suites, Troughs, Basins, Tapware'),
('AU',81,'700','Insulation to Ceilings'),
('AU',82,'710','Int. Cleaner (Pre-Clean Sweep)'),
('AU',83,'720','Joint Sealing and Caulking'),
('AU',84,'730','Retaining Walls - Landscaping'),
('AU',85,'740','Concrete Paving & Driveway'),
('AU',86,'741','Paving Accessories'),
('AU',87,'760','Termite Perimeter Treatment'),
('AU',88,'770','Window & Door Screens'),
('AU',89,'780','Clothes Line & Letterbox'),
('AU',90,'790','Window Coverings'),
('AU',91,'805','Timber Flooring'),
('AU',92,'810','Carpet & Floor Coverings'),
('AU',93,'820','Fencing'),
('AU',94,'830','Internal Cleaner'),
('AU',95,'840','Landscaping - Labour & Material'),
('AU',96,'858','Materials - Pergolas & Decks'),
('AU',97,'860','Carpenter - Pergolas & Decks'),
('AU',98,'870','Appliances - Electric and Gas'),
('AU',99,'880','HWS & Solar Collectors'),
('AU',100,'890','Rainwater Tanks'),
('AU',101,'900','Settlement Internal Re-Clean'),
('AU',102,'901','Appliance Internal Re-Clean'),
('AU',103,'910','Site Cleaner - Final'),
('AU',104,'918','Quality Assurance Touch Ups'),
('AU',105,'920','Quality Assurance Inspection');

-- ── GENERIC (international neutral) — no cost centres, edit/add to suit ───────
delete from public.trade_presets where region = 'GENERIC';
insert into public.trade_presets (region, sort, code, name) values
('GENERIC',1,null,'Site Preparation'),
('GENERIC',2,null,'Earthworks & Excavation'),
('GENERIC',3,null,'Foundations & Concrete'),
('GENERIC',4,null,'Drainage'),
('GENERIC',5,null,'Framing & Structure'),
('GENERIC',6,null,'Bricklaying & Masonry'),
('GENERIC',7,null,'Roofing'),
('GENERIC',8,null,'Guttering & Fascia'),
('GENERIC',9,null,'Scaffolding'),
('GENERIC',10,null,'Windows & Doors'),
('GENERIC',11,null,'Waterproofing'),
('GENERIC',12,null,'Insulation'),
('GENERIC',13,null,'Plumbing'),
('GENERIC',14,null,'Electrical'),
('GENERIC',15,null,'Heating & Cooling (HVAC)'),
('GENERIC',16,null,'Plastering & Drywall'),
('GENERIC',17,null,'Rendering'),
('GENERIC',18,null,'Carpentry'),
('GENERIC',19,null,'Cabinetry & Joinery'),
('GENERIC',20,null,'Tiling'),
('GENERIC',21,null,'Painting'),
('GENERIC',22,null,'Flooring'),
('GENERIC',23,null,'Glazing & Mirrors'),
('GENERIC',24,null,'Staircase'),
('GENERIC',25,null,'Plumbing Fixtures'),
('GENERIC',26,null,'Garage Doors'),
('GENERIC',27,null,'Appliances'),
('GENERIC',28,null,'Hot Water System'),
('GENERIC',29,null,'Cladding'),
('GENERIC',30,null,'Decking'),
('GENERIC',31,null,'Fencing'),
('GENERIC',32,null,'Driveway & Paving'),
('GENERIC',33,null,'Landscaping'),
('GENERIC',34,null,'Stone & Benchtops'),
('GENERIC',35,null,'Solar'),
('GENERIC',36,null,'Pest Control'),
('GENERIC',37,null,'Cleaning'),
('GENERIC',38,null,'Final Inspection & QA');

-- ── US (United States) — DRAFT, builder to refine ───────────────────────────
delete from public.trade_presets where region = 'US';
insert into public.trade_presets (region, sort, code, name) values
('US',1,null,'Site Preparation'),
('US',2,null,'Excavation & Grading'),
('US',3,null,'Foundation & Concrete'),
('US',4,null,'Framing'),
('US',5,null,'Roofing'),
('US',6,null,'Siding'),
('US',7,null,'Windows & Exterior Doors'),
('US',8,null,'Plumbing Rough-In'),
('US',9,null,'Electrical Rough-In'),
('US',10,null,'HVAC'),
('US',11,null,'Insulation'),
('US',12,null,'Drywall'),
('US',13,null,'Interior Trim & Carpentry'),
('US',14,null,'Cabinetry'),
('US',15,null,'Countertops'),
('US',16,null,'Painting'),
('US',17,null,'Flooring'),
('US',18,null,'Tile'),
('US',19,null,'Plumbing Fixtures'),
('US',20,null,'Electrical Fixtures'),
('US',21,null,'Garage Doors'),
('US',22,null,'Gutters'),
('US',23,null,'Masonry & Brick'),
('US',24,null,'Stucco'),
('US',25,null,'Waterproofing'),
('US',26,null,'Decking'),
('US',27,null,'Fencing'),
('US',28,null,'Landscaping'),
('US',29,null,'Flatwork & Driveway'),
('US',30,null,'Appliances'),
('US',31,null,'Water Heater'),
('US',32,null,'Low Voltage & Data'),
('US',33,null,'Fire Sprinklers'),
('US',34,null,'Stairs & Railings'),
('US',35,null,'Glass, Mirrors & Shower'),
('US',36,null,'Septic & Sewer'),
('US',37,null,'Solar'),
('US',38,null,'Pest Control'),
('US',39,null,'Retaining Walls'),
('US',40,null,'Final Clean'),
('US',41,null,'Punch List & QA');

-- ── UK (United Kingdom) — DRAFT, builder to refine ──────────────────────────
delete from public.trade_presets where region = 'UK';
insert into public.trade_presets (region, sort, code, name) values
('UK',1,null,'Site Setup & Welfare'),
('UK',2,null,'Groundworks & Excavation'),
('UK',3,null,'Foundations & Concrete'),
('UK',4,null,'Drainage'),
('UK',5,null,'Brickwork & Blockwork'),
('UK',6,null,'Structural Steel'),
('UK',7,null,'Roof Trusses & Carpentry (1st Fix)'),
('UK',8,null,'Roofing & Tiling'),
('UK',9,null,'Fascias, Soffits & Guttering'),
('UK',10,null,'Scaffolding'),
('UK',11,null,'Windows & External Doors'),
('UK',12,null,'Damp Proofing'),
('UK',13,null,'Plumbing 1st Fix'),
('UK',14,null,'Electrical 1st Fix'),
('UK',15,null,'Heating & Boiler'),
('UK',16,null,'Insulation'),
('UK',17,null,'Plastering & Plasterboard'),
('UK',18,null,'Rendering'),
('UK',19,null,'Joinery 2nd Fix'),
('UK',20,null,'Kitchen Units'),
('UK',21,null,'Wall & Floor Tiling'),
('UK',22,null,'Painting & Decorating'),
('UK',23,null,'Flooring & Carpets'),
('UK',24,null,'Plumbing 2nd Fix & Sanitaryware'),
('UK',25,null,'Electrical 2nd Fix'),
('UK',26,null,'Staircase'),
('UK',27,null,'Glazing & Splashbacks'),
('UK',28,null,'Driveways & Paving'),
('UK',29,null,'Landscaping & Turfing'),
('UK',30,null,'Fencing & Gates'),
('UK',31,null,'Garage Doors'),
('UK',32,null,'Appliances'),
('UK',33,null,'Loft & Insulation'),
('UK',34,null,'Plumbing Fixtures'),
('UK',35,null,'Solar PV'),
('UK',36,null,'Pest Control'),
('UK',37,null,'Final Clean'),
('UK',38,null,'Snagging & QA');

-- ── Region-aware create_organization (drop old single-arg form first) ────────
drop function if exists public.create_organization(text);

create or replace function public.create_organization(p_name text, p_region text default 'AU')
returns uuid language plpgsql security definer set search_path = public as $$
declare new_id uuid; v_region text;
begin
  v_region := upper(coalesce(nullif(trim(p_region), ''), 'AU'));
  if not exists (select 1 from trade_presets where region = v_region) then
    v_region := 'GENERIC';
  end if;
  insert into organizations (name, created_by, region)
    values (p_name, auth.uid(), v_region) returning id into new_id;
  insert into org_members (org_id, user_id, role)
    values (new_id, auth.uid(), 'owner');
  insert into trades (org_id, legacy_id, name, code)
    select new_id, sort, name, code from trade_presets
    where region = v_region order by sort;
  return new_id;
end; $$;
